#!/usr/bin/env python3
"""Rebuild assets/fonts/ — the self-hosted webfonts the page serves itself.

    python3 tools/build_fonts.py

Fetches the Google Fonts CSS2 payload for the families the page uses,
downloads every woff2 it names, and writes assets/fonts/fonts.css with
relative URLs. Only the scripts the page renders are kept (Latin, Latin-ext,
Greek, Greek-ext, Arabic); Cyrillic, Vietnamese and the symbol subsets are
dropped, which is most of the weight. unicode-range is preserved, so an
English visitor downloads only the Latin faces.

Run this after changing a font family or weight in index.html, then rerun
tools/preflight.py. Needs network access; nothing else does.
"""
import os
import re
import shutil
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'fonts')
KEEP = {'latin', 'latin-ext', 'greek', 'greek-ext', 'arabic'}

# Must stay in step with the families and weights index.html asks for.
FAMILIES = ('Barlow+Condensed:ital,wght@0,700;0,800;1,300'
            '&family=Barlow:wght@500;600;700'
            '&family=Inter:wght@400'
            '&family=Montserrat:wght@700'
            '&family=Cairo:wght@400;500;600;700;800'
            '&family=Roboto+Condensed:ital,wght@0,400;0,700;0,800;1,300'
            '&family=Roboto:wght@400;500;600;700')
CSS_URL = 'https://fonts.googleapis.com/css2?family=%s&display=swap' % FAMILIES
# woff2 is only offered to a UA that advertises support
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0 Safari/537.36')


def get(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    return urllib.request.urlopen(req, timeout=60).read()


try:
    css = get(CSS_URL).decode('utf-8')
except Exception as exc:                                   # noqa: BLE001
    sys.exit('could not fetch the font CSS (%s).\nThis script is the only '
             'part of the project that needs network access; the committed\n'
             'assets/fonts/ directory is what the site actually serves.' % exc)

blocks = re.findall(r'/\*\s*([^*]+?)\s*\*/\s*(@font-face\s*\{[^}]*\})', css)
if not blocks:
    sys.exit('the font CSS came back in an unexpected shape; not overwriting '
             'assets/fonts/')

kept, remote = [], {}
for label, blk in blocks:
    if label not in KEEP:
        continue
    url = re.search(r'url\((https://[^)]+)\)', blk).group(1)
    name = url.rsplit('/', 1)[-1]
    if not name.endswith('.woff2'):
        sys.exit('got %s instead of woff2 — check the User-Agent' % name)
    remote[name] = url
    kept.append('/* %s */\n%s' % (label, blk.replace(url, 'f/' + name)))

tmp = OUT + '.new'
shutil.rmtree(tmp, ignore_errors=True)
os.makedirs(os.path.join(tmp, 'f'))
total = 0
for name, url in sorted(remote.items()):
    data = get(url)
    open(os.path.join(tmp, 'f', name), 'wb').write(data)
    total += len(data)

header = """/* Self-hosted webfonts — the page makes no third-party requests.
   Generated by tools/build_fonts.py; do not hand-edit. Pruned to the scripts
   this page renders (Latin, Latin-ext, Greek, Greek-ext, Arabic), with
   unicode-range preserved so each visitor downloads only what their text
   needs. Licences are in LICENSES/. */

"""
open(os.path.join(tmp, 'fonts.css'), 'w', encoding='utf-8').write(
    header + '\n'.join(kept) + '\n')

# keep the licence files across a rebuild
lic = os.path.join(OUT, 'LICENSES')
if os.path.isdir(lic):
    shutil.copytree(lic, os.path.join(tmp, 'LICENSES'))
shutil.rmtree(OUT, ignore_errors=True)
os.rename(tmp, OUT)

print('assets/fonts: %d faces, %d files, %.0f KB' % (len(kept), len(remote), total / 1024))
